text={
  "Reggel felébredtem. Mit tegyek?": "I woke up in the morning. What should I do?",
  "fogmosás": "brushing teeth",
  "reggeli": "breakfast",
  "Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!": "I go to brush my teeth. I clean them thoroughly, as needed!",
  "öltözés": "dressing",
  "Kellene valamit enni! Anya csinált valamit? Nézzük meg! \nHamm Hamm! Fincsi!": "I should eat something! Did mom make something? Let's see! \nYum Yum! Delicious!",
  "Kissé hűvös van, kellene valami ruha. \nFelveszek egy nadrágot, meg egy pólót!": "It's a bit chilly; I need some clothes. \nI put on pants and a T-shirt!",
  "Véde mindennek....": "Protect everything...",
  "66-os parancs": "Order 66",
  "asd": "asd",
  "Elindultam a buszmegállóba. \nMelyik buszra szálljak fel?": "I headed to the bus stop. \nWhich bus should I take?",
  "6:50": "6:50",
  "7:05": "7:05",
  "7:20": "7:20",
  "Elindulok a buszmegállóba": "I'm heading to the bus stop",
  "Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell": "I got on the bus at 6:50, there are a lot of people, so I have to stand",
  "buszról leszállva várjam meg a barátaimat": "Get off the bus and wait for my friends",
  "buszról leszállva menjek a boltba": "Get off the bus and go to the store",
  "buszról leszállva menjek az iskolába": "Get off the bus and go to school",
  "Felszálltam a 7:05-ös buszra, sikerült egy helyet szereznem, így letudtam ülni": "I got on the bus at 7:05, managed to get a seat, so I could sit down",
  "Felszálltam a 7:20-as buszra, nem voltak a buszon, így leültem.\nTaláltam a földön 500Ft-ot": "I got on the bus at 7:20, there were no people, so I sat down.\nFound 500 HUF on the ground",
  "Szóljak a sofőrnek és adjam neki": "Should I tell the driver and give it to him",
  "Hagyjam ott": "Leave it",
  "Vigyem el": "Take it with me",
  "A sofőr hülyén néz rám, miközben zsebre teszi a pénzt": "The driver looks at me strangely while putting the money in his pocket",
  "A földön hagytam a pénzt, én hülye!": "I left the money on the ground, I'm silly!",
  "A pént boldogan felvettem a földről( :) ).": "I happily picked up the money from the ground ( :) ).",
  "Suliba menet elajándékozom a pénzt egy hajléktalannak": "On the way to school, I give the money to a homeless person",
  "buszról leszállva várjam meg a barátaimat": "Get off the bus and wait for my friends",
  "buszról leszállva menjek az iskolába": "Get off the bus and go to school",
  "A csöves örült a pénznek, szebbé tettem a napját\nAmiért kedves votam, kaptam tőle egy szuperkártyát": "The homeless person was happy about the money; I made his day better\nBecause I was kind, he gave me a supercard",
  "A suliba beérve menjek a teremhez": "Upon arriving at school, go to the classroom",
  "A suliba beérve menjek a barátaimhoz": "Upon arriving at school, go to my friends",
  "megvártam a barátaimat és együtt mentünk iskolába. ": "I waited for my friends, and we went to school together.",
  "a suliba beérve menjünk együtt a teremhez": "Upon arriving at school, let's go to the classroom together",
  "Suliba beérve menjünk a többiekhez": "Upon arriving at school, let's go to the others",
  "Egyedül megyek az iskolába, útközben találkoztam a barátaimmal.": "I go to school alone, and on the way, I met my friends.",
  "Odaértünk a teremhez. Ott voltak a többiek. \nNagyon kell pipilni": "We arrived at the classroom. The others were there. \nI really need to pee",
  "óráról majd kikéretőzök":"I will ask to be excused from class later",
  "menjek el WC-re": "Go to the restroom",
  "Pipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?":"I peed \nOops! A bit to the side. Oops! ÁÁÁÁÁÁ! \nYou fell and hit your head...\nI woke up in an underground room. What should I do?",
  "Nézzek körül":"Look around",
  "Elmentem pipilni...\nPipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél a saját pipidben és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?":"I went to pee... \nI peed. Oh, I veered off a bit. Oops! AAAAAA! \nYou fell in your own pee and hit your head... \nI woke up in an underground room. What should I do?",
  "Keressek kijáratot": "Search for an exit",
  "Körülnéztem, csupán egy út vezet kifelé a szobából": "I looked around, there is only one way out of the room",
  "kimenjek rajta":"Go out through it",
  "Várjak, hátha csak képzelődöm": "Wait, maybe I'm just imagining things",
  "Körülnézzek mégegyszer":"Look around again",
 

 "Ez nem képzelődés, jobb lenne inkább körülnézni:)": "This is not imagination; it would be better to look around :)",
  "Körülnézek": "I look around",
  "Jobb oldali kopott ajtó": "Right side worn door",
  "Középső fehér ajtó": "Middle white door",
  "Bal oldali kopott ajtó": "Left side worn door",
  "Kimentem az ajtón, a másik szobában 3 ajtót látok. \nMelyiken menjek be?": "I went out the door, in the other room, I see 3 doors. \nWhich one should I enter?",
  "Körülnéztél mégyegyszer, és találtál egy titkos ajtót": "You looked around once more and found a secret door",
  "Bemegyek rajta": "I go in through it",
  "Inkább a korábban felfedezett kijáratot választom": "I choose the previously discovered exit instead",
  "Bementél a jobb oldali ajtón. \nBent eldobált fegyverek és egy 200 centis páncélos harcos áll veled szemben, aki feléd közelít.": "You went in through the right-side door. \nInside, there are scattered weapons, and a 200 cm armored warrior is approaching you.",
  "Felkapsz egyet a régi fegyverek közül és nekirontasz": "You pick up one of the old weapons and charge at him",
  "Kifutsz a szobából, hátha nem követ": "You run out of the room, maybe he won't follow",
  "Mivel más kijáratot nem látsz kimész": "Since you don't see another exit, you leave",
  "Könnyítesz magadon mert ismét kell": "You relieve yourself because you need to again",
  "Mivel más kijáratot nem látsz kimész vissza": "Since you don't see another exit, you leave back",
  "Bementél a bal oldali ajtón. \n Egy sárkány rohan feléd": "You went in through the left-side door. \n A dragon rushes towards you",
  "Megpróbálsz elfutni": "You try to run away",
  "Felkapsz egy lándzsát ami a padlón hever és rátámadsz": "You pick up a spear lying on the floor and attack",
  "ajtó": "door",
  "Bementél a középső ajtón. Egy WC-ben találod magad": "You went in through the middle door. You find yourself in a toilet",
  "Bementél a középső ajtón. Egy WC-ben találod magad": "You went in through the middle door. You find yourself in a toilet",
  "Könnyítesz magadon mert ismét kell": "You relieve yourself because you need to again",
  "Mivel más kijáratot nem látsz kimész vissza": "Since you don't see another exit, you leave back",
  "Felkapsz egy lándzsát ami a padlón hever és rátámadsz": "You pick up a spear lying on the floor and attack",
  "Kimaradsz a megbeszélésből": "You stay out of the discussion",
  "Megpróbálsz elfutni": "You try to run away",
  "Csatlakozol te is a terv megbeszéléséhez": "You join the plan discussion",
  "Benyitsz a titkos ajtón, ami egy mély aknába nyílik.\n Leesel a mélybe, ahol más hozzád hasonló pisiben elcsúszó kölök tervezi a szabadulást.": "You open the secret door, which leads to a deep pit.\n You fall into the deep, where other kids like you, slipping in pee, plan the escape.",
  "Mivel kimaradtál, nem bírták a képed...\n péppé lettél verve...(R.I.P.)": "Since you missed, they couldn't handle it...\n you were beaten to a pulp...(R.I.P.)",
  "Kifutsz és eltorlaszolod az ajtót a folyosón lévő szekrénnyel. \nMelyik másik ajtót válasszam?": "You run out and barricade the door with a cabinet in the hallway. \nWhich other door should I choose?",
  "A lovag kiüti a kezedből a kardot és földhözvág. Ez bukta!!": "The knight knocks the sword out of your hand and throws you to the ground. That's a loss!!",
  "Megbeszéltétek, hogy felmásztok a szakadékba...\n hát nem leestél? (de) \n legalább szépet estél...\nThe End": "You agreed to climb into the gap...\n but didn't you fall? (but) \n at least you fell beautifully...\nThe End",
  "A lovag kiüti a kezedből a kardot és földhözvág. Ez bukta!!\nThe End": "The knight knocks the sword out of your hand and throws you to the ground. That's a loss!!\nThe End",
  "Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben\nThe End": "Finally, I peed again.\n ÁÁÁÁÁÁÁÁ! \nAgain, you fell and hit your head...\n you woke up in the school restroom\nThe End",
  "A sárkány tüzet okád rád, majd az égő fájdalom közben rángatózva felébredsz a suli WC-ben :)\nThe End": "The dragon breathes fire on you, then, in the burning pain, you wake up twitching in the school restroom :)",
  "Mivel kimaradtál, nem bírták a képed...\n péppé lettél verve...(R.I.P.)\nThe End": "Since you missed, they couldn't handle it...\n you were beaten to a pulp...(R.I.P.)\nThe End",
  "Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben":"I finally peed again.\n Oh no! You fell again and hit your head... \n You woke up in the school bathroom.",
      

      
      
      
 
   }
