text={"Reggel felébredtem. Mit tegyek?":"Reggel felébredtem. Mit tegyek?",
          "fogmosás":"fogmosás",
          "reggeli":"reggeli",
      "Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!":"Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!",
          "öltözés":"öltözés",
      "Kellene valamit enni! Anya csinált valamit? Nézzük meg!":"Kellene valamit enni! Anya csinált valamit? Nézzük meg!",
      "Kissé hűvös van, kellene valami ruha. \nFelveszek egy nadrágot, meg egy pólót!":"Kissé hűvös van, kellene valami ruha. \nFelveszek egy nadrágot, meg egy pólót!",
      "Véde mindennek....":"Véde mindennek....",
      "66-os parancs":"66-os parancs",
      "asd":"asd",
      "Elindultam a buszmegállóba. \nMelyik buszra szálljak fel?": "Elindultam a buszmegállóba. \nMelyik buszra szálljak fel?",
      "6:50":"6:50",
      "7:05":"7:05",
      "7:20":"7:20",
      "Elindulok a buszmegállóba":"Elindulok a buszmegállóba",
      "Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell":"Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell",
      "buszról leszállva várjam meg a barátaimat":"buszról leszállva várjam meg a barátaimat",
      "buszról leszállva menjek a boltba":"buszról leszállva menjek a boltba",
      "buszról leszállva menjek az iskolába":"buszról leszállva menjek az iskolába",
      "Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell":"Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell",
      "Felszálltam a 7:05-ös buszra, sikerült egy helyet szereznem, így letudtam ülni":"Felszálltam a 7:05-ös buszra, sikerült egy helyet szereznem, így letudtam ülni",
      "Felszálltam a 7:20-as buszra, nem voltak a buszon, így leültem.\nTaláltam a földön 500Ft-ot":"Felszálltam a 7:20-as buszra, nem voltak a buszon, így leültem.\nTaláltam a földön 500Ft-ot",
      "Szóljak a sofőrnek és adjam neki":"Szóljak a sofőrnek és adjam neki",
      "Hagyjam ott":"Hagyjam ott",
      "Vigyem el":"Vigyem el",
      "A sofőr hülyén néz rám, miközben zsebre teszi a pénzt":"A sofőr hülyén néz rám, miközben zsebre teszi a pénzt",
      "A földön hagytam a pénzt, én hülye!":"A földön hagytam a pénzt, én hülye!",
      "A pént boldogan felvettem a földről( :) ).":"A pént boldogan felvettem a földről( :) ).",
      "Suliba menet elajándékozom a pénzt egy hajléktalannak":"Suliba menet elajándékozom a pénzt egy hajléktalannak",
      "buszról leszállva várjam meg a barátaimat":"buszról leszállva várjam meg a barátaimat",
      "buszról leszállva menjek az iskolába":"buszról leszállva menjek az iskolába",
      "A csöves örült a pénznek, szebbé tettem a napját\nAmiért kedves votam, kaptam tőle egy szuperkártyát":"A csöves örült a pénznek, szebbé tettem a napját\nAmiért kedves votam, kaptam tőle egy szuperkártyát",
      "A suliba beérve menjek a teremhez":"A suliba beérve menjek a teremhez",
      "A suliba beérve menjek a barátaimhoz":"A suliba beérve menjek a barátaimhoz",
      "megvártam a barátaimat és együtt mentünk iskolába. ":"megvártam a barátaimat és együtt mentünk iskolába. ",
      "a suliba beérve menjünk együtt a teremhez":"a suliba beérve menjünk együtt a teremhez",
      "Suliba beérve menjünk a többiekhez":"Suliba beérve menjünk a többiekhez",
      "Egyedül megyek az iskolába, útközben találkoztam a barátaimmal.":"Egyedül megyek az iskolába, útközben találkoztam a barátaimmal.",
      "Odaértünk a teremhez. Ott voltak a többiek. \nNagyon kell pipilni":"Odaértünk a teremhez. Ott voltak a többiek. \nNagyon kell pipilni",
      "óráról majd kikéretőzök":"óráról majd kikéretőzök",
      "menjek el WC-re":"menjek el WC-re",
      "Pipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?":"Pipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?",
      "Nézzek körül":"Nézzek körül",
      "Keressek kijáratot":"Keressek kijáratot",
      "Körülnéztem, csupán egy út vezet kifelé a szobából":"Körülnéztem, csupán egy út vezet kifelé a szobából",
      "kimenjek rajta":"kimenjek rajta",
      "Várjak, hátha csak képzelődöm":"Várjak, hátha csak képzelődöm",
      "Körülnézzek mégegyszer":"Körülnézzek mégegyszer",
      "Ez nem képzelődés, jobb lenne inkább körülnézni:)":"Ez nem képzelődés, jobb lenne inkább körülnézni:)",
      "Körülnézek":"Körülnézek",
      
      

      
      
      
 
   }
