text={"Reggel felébredtem. Mit tegyek?":"Reggel felébredtem. Mit tegyek?",
          "fogmosás":"fogmosás",
          "reggeli":"reggeli",
      "Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!":"Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!",
          "öltözés":"öltözés",
      "Kellene valamit enni! Anya csinált valamit? Nézzük meg! \nHamm Hamm! Fincsi!":"Kellene valamit enni! Anya csinált valamit? Nézzük meg! \nHamm Hamm! Fincsi!",
      "Kissé hűvös van, kellene valami ruha. \nFelveszek egy nadrágot, meg egy pólót!":"Kissé hűvös van, kellene valami ruha. \nFelveszek egy nadrágot, meg egy pólót!",
      "Véde mindennek....":"Véde mindennek....",
      "66-os parancs":"66-os parancs",
      "asd":"asd",
      "Elindultam a buszmegállóba. \nMelyik buszra szálljak fel?": "Elindultam a buszmegállóba. \nMelyik buszra szálljak fel?",
      "6:50":"6:50",
      "7:05":"7:05",
      "7:20":"7:20",
      "Elindulok a buszmegállóba":"Elindulok a buszmegállóba",
      "Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell":"Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell",

      "buszról leszállva várjam meg a barátaimat":"buszról leszállva várjam meg a barátaimat",
      "buszról leszállva menjek a boltba":"buszról leszállva menjek a boltba",
      "buszról leszállva menjek az iskolába":"buszról leszállva menjek az iskolába",
      "Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell":"Felszálltam a 6:50-es buszra, nagyon sokan vannak, így álnom kell",
      "Felszálltam a 7:05-ös buszra, sikerült egy helyet szereznem, így letudtam ülni":"Felszálltam a 7:05-ös buszra, sikerült egy helyet szereznem, így letudtam ülni",
      "Felszálltam a 7:20-as buszra, nem voltak a buszon, így leültem.\nTaláltam a földön 500Ft-ot":"Felszálltam a 7:20-as buszra, nem voltak a buszon, így leültem.\nTaláltam a földön 500Ft-ot",
      "Szóljak a sofőrnek és adjam neki":"Szóljak a sofőrnek és adjam neki",
      "Hagyjam ott":"Hagyjam ott",
      "Vigyem el":"Vigyem el",
      "A sofőr hülyén néz rám, miközben zsebre teszi a pénzt":"A sofőr hülyén néz rám, miközben zsebre teszi a pénzt",
      "A földön hagytam a pénzt, én hülye!":"A földön hagytam a pénzt, én hülye!",
      "A pént boldogan felvettem a földről( :) ).":"A pént boldogan felvettem a földről( :) ).",
      "Suliba menet elajándékozom a pénzt egy hajléktalannak":"Suliba menet elajándékozom a pénzt egy hajléktalannak",
      "buszról leszállva várjam meg a barátaimat":"buszról leszállva várjam meg a barátaimat",
      "buszról leszállva menjek az iskolába":"buszról leszállva menjek az iskolába",
      "A csöves örült a pénznek, szebbé tettem a napját\nAmiért kedves votam, kaptam tőle egy szuperkártyát":"A csöves örült a pénznek, szebbé tettem a napját\nAmiért kedves votam, kaptam tőle egy szuperkártyát",
      "A suliba beérve menjek a teremhez":"A suliba beérve menjek a teremhez",
      "A suliba beérve menjek a barátaimhoz":"A suliba beérve menjek a barátaimhoz",
      "megvártam a barátaimat és együtt mentünk iskolába. ":"megvártam a barátaimat és együtt mentünk iskolába. ",
      "a suliba beérve menjünk együtt a teremhez":"a suliba beérve menjünk együtt a teremhez",
      "Suliba beérve menjünk a többiekhez":"Suliba beérve menjünk a többiekhez",
      "Egyedül megyek az iskolába, útközben találkoztam a barátaimmal.":"Egyedül megyek az iskolába, útközben találkoztam a barátaimmal.",
      "Odaértünk a teremhez. Ott voltak a többiek. \nNagyon kell pipilni":"Odaértünk a teremhez. Ott voltak a többiek. \nNagyon kell pipilni",
      "óráról majd kikéretőzök":"óráról majd kikéretőzök",
      "menjek el WC-re":"menjek el WC-re",
      "Pipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?":"Pipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?",
      "Nézzek körül":"Nézzek körül",
      "Keressek kijáratot":"Keressek kijáratot",
      "Körülnéztem, csupán egy út vezet kifelé a szobából":"Körülnéztem, csupán egy út vezet kifelé a szobából",
      "kimenjek rajta":"kimenjek rajta",
      "Várjak, hátha csak képzelődöm":"Várjak, hátha csak képzelődöm",
      "Körülnézzek mégegyszer":"Körülnézzek mégegyszer",
      "Ez nem képzelődés, jobb lenne inkább körülnézni:)":"Ez nem képzelődés, jobb lenne inkább körülnézni:)",
      "Körülnézek":"Körülnézek",

      "Jobb oldali kopott ajtó":"Jobb oldali kopott ajtó",
      "Középső fehér ajtó":"Középső fehér ajtó",
      "Bal oldali kopott ajtó":"Bal oldali kopott ajtó",
      "Kimentem az ajtón, a másik szobában 3 ajtót látok. \nMelyiken menjek be?":"Kimentem az ajtón, a másik szobában 3 ajtót látok. \nMelyiken menjek be?",
      "Körülnéztél mégyegyszer, és találtál egy titkos ajtót":"Körülnéztél mégyegyszer, és találtál egy titkos ajtót",
      "Bemegyek rajta":"Bemegyek rajta",
      "Inkább a korábban felfedezett kijáratot választom":"Inkább a korábban felfedezett kijáratot választom",
      "Bementél a jobb oldali ajtón. \nBent eldobált fegyverek és egy 200 centis páncélos harcos áll veled szemben, aki feléd közelít.":"Bementél a jobb oldali ajtón. \nBent eldobált fegyverek és egy 200 centis páncélos harcos áll veled szemben, aki feléd közelít.",
      "Felkapsz egyet a régi fegyverek közül és nekirontasz":"Felkapsz egyet a régi fegyverek közül és nekirontasz",
      "Kifutsz a szobából, hátha nem követ":"Kifutsz a szobából, hátha nem követ",
      "Mivel más kijáratot nem látsz kimész":"Mivel más kijáratot nem látsz kimész",
      "Könnyítesz magadon mert ismét kell":"Könnyítesz magadon mert ismét kell",
      "Mivel más kijáratot nem látsz kimész vissza":"Mivel más kijáratot nem látsz kimész vissza",
      "Bementél a bal oldali ajtón. \n Egy sárkány rohan feléd":"Bementél a bal oldali ajtón. \n Egy sárkány rohan feléd",
      "Megpróbálsz elfutni":"Megpróbálsz elfutni",
      "Felkapsz egy lándzsát ami a padlón hever és rátámadsz":"Felkapsz egy lándzsát ami a padlón hever és rátámadsz",
      "ajtó":"ajtó",
      "Bementél a középső ajtón. Egy WC-ben találod magad":"Bementél a középső ajtón. Egy WC-ben találod magad",
      "Bementél a középső ajtón. Egy WC-ben találod magad":"Bementél a középső ajtón. Egy WC-ben találod magad",
      "Könnyítesz magadon mert ismét kell":"Könnyítesz magadon mert ismét kell",
      "Mivel más kijáratot nem látsz kimész vissza":"Mivel más kijáratot nem látsz kimész vissza",
      "Felkapsz egy lándzsát ami a padlón hever és rátámadsz":"Felkapsz egy lándzsát ami a padlón hever és rátámadsz",
      "Kimaradsz a megbeszélésből":"Kimaradsz a megbeszélésből",
      "Megpróbálsz elfutni":"Megpróbálsz elfutni",
      "Csatlakozol te is a terv megbeszéléséhez":"Csatlakozol te is a terv megbeszéléséhez",
      "Benyitsz a titkos ajtón, ami egy mély aknába nyílik.\n Leesel a mélybe, ahol más hozzád hasonló pisiben elcsúszó kölök tervezi a szabadulást.":"Benyitsz a titkos ajtón, ami egy mély aknába nyílik.\n Leesel a mélybe, ahol más hozzád hasonló pisiben elcsúszó kölök tervezi a szabadulást.",
      "Mivel kimaradtál, nem bírták a képed...\n péppé lettél verve...(R.I.P.)":"Mivel kimaradtál, nem bírták a képed...\n péppé lettél verve...(R.I.P.)",
      "Kifutsz és eltorlaszolod az ajtót a folyosón lévő szekrénnyel. \nMelyik másik ajtót válasszam?":"Kifutsz és eltorlaszolod az ajtót a folyosón lévő szekrénnyel. \nMelyik másik ajtót válasszam?",
      "A lovag kiüti a kezedből a kardot és földhözvág. Ez bukta!!":"A lovag kiüti a kezedből a kardot és földhözvág. Ez bukta!!",
      "Megbeszéltétek, hogy felmásztok a szakadékba...\n hát nem leestél? (de) \n legalább szépet estél...\nThe End":"Megbeszéltétek, hogy felmásztok a szakadékba...\n hát nem leestél? (de) \n legalább szépet estél...\nThe End",
      "A lovag kiüti a kezedből a kardot és földhözvág. Ez bukta!!\nThe End":"A lovag kiüti a kezedből a kardot és földhözvág. Ez bukta!!\nThe End",
      "Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben\nThe End":"Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben\nThe End",
      "A sárkány tüzet okád rád, majd az égő fájdalom közben rángatózva felébredsz a suli WC-ben :)\nThe End":"A sárkány tüzet okád rád, majd az égő fájdalom közben rángatózva felébredsz a suli WC-ben :)\nThe End",
      "Mivel kimaradtál, nem bírták a képed...\n péppé lettél verve...(R.I.P.)\nThe End":"Mivel kimaradtál, nem bírták a képed...\n péppé lettél verve...(R.I.P.)\nThe End",
      "Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben":"Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben",
    
      "Kimentem az ajtón, a másik szobában 3 ajtót látok. \nMelyiken menjek be?":"Kimentem az ajtón, a másik szobában 3 ajtót látok. \nMelyiken menjek be?",
      "Elmentem pipilni...\nPipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél a saját pipidben és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?":"Elmentem pipilni...\nPipiltem \nÓ kicsit mellément. Hoppá! ÁÁÁÁÁÁ! \nElestél a saját pipidben és beverted a fejedet...\nEgy földalatti szobában ébredtem fel. Mit tegyek?",
      "A sárkány tüzet okád rád, majd az égő fájdalom közben rángatózva felébredsz a suli WC-ben :)":"A sárkány tüzet okád rád, majd az égő fájdalom közben rángatózva felébredsz a suli WC-ben :)",
      "Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben":"Végre újra pipiltem.\n ÁÁÁÁÁÁÁÁ! \nMár megint elestél és beverted a fejed...\n felébredtél a suli WC-ben",
      
      

      
      
      
 
   }

